### ISSUE TITLE
Tambah Tombol Edit Pegawai

### ISSUE THREAD

**Issue by pemdestangkolo** [mirzaramadhany/webapp_sppd#2]
Mohon tambahkan fungsi Edit Data Pegawai yang sudah tersimpan di halaman Master Pegawai.
Terima Kasih

**Comment by mirzaramadhany** [comment]
Tombol edit sudah ada disebelah kanan silahkan geser daftar ke kanan
- 
Jika membutuhkan aplikasi yang lebih detil dan berhubungan dengan dinas silahkan hubungi kami. 
Terima Kasih
